<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="#">DashFwd Demo</a>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item <#if selectedNav=="people">active</#if>">
                <a class="nav-link" href="/">People <span class="sr-only">(current)</span></a>
            </li>
        </ul>
    </div>
</nav>
<div style="height:80px"></div>
